name: Azure CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: azcheckin-func
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  AZURE_STATICWEBAPP_SOURCE_PATH: '/'
  AZURE_STATICWEBAPP_OUTPUT_PATH: 'dist/azure-checkin'
  NODE_VERSION: '14.x'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
        env:
          CI: true
      - run: npx semantic-release
        if: success() && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: ${{ env.AZURE_STATICWEBAPP_SOURCE_PATH }}
          api_location: '' # Disabled as we provide our own Function App
          output_location: ${{ env.AZURE_STATICWEBAPP_OUTPUT_PATH }}
